/**
 * DTOs = Data Transfer Objects
 * Aligned with @ensemble-react/js-commons core/dto.ts
 * https://github.com/EnsembleUI/ensemble-react/blob/main/packages/js-commons/src/core/dto.ts
 */

export interface HasManifest {
  manifest?: Record<
    string,
    Partial<EnsembleDocument> & {
      relativePath?: string;
    }
  >;
}

export interface EnsembleDocument {
  readonly id: string;
  readonly name: string;
  readonly content: string;
  readonly type: EnsembleDocumentType;

  readonly description?: string;
  readonly isRoot?: boolean;
  readonly isDraft?: boolean;
  readonly isArchived?: boolean;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  readonly createdBy?: {
    name: string;
    email?: string;
    id: string;
  };
  readonly updatedBy?: {
    name: string;
    email?: string;
    id: string;
  };
}

export enum EnsembleDocumentType {
  I18n = 'i18n',
  Theme = 'theme',
  Asset = 'asset',
  Screen = 'screen',
  Font = 'font',
  Widget = 'internal_widget',
  Script = 'internal_script',
  Environment = 'config',
  Secrets = 'secrets',
  Label = 'label',
}

export interface ApplicationDTO
  extends Omit<EnsembleDocument, 'type' | 'content'>,
    HasManifest {
  readonly isReact?: boolean;
  readonly isAutoGenerated?: boolean;
  readonly status?: string;
  readonly category?: AppCategory;
  readonly collaborators?: Record<string, AccessType>;
  readonly demoOrder?: number;
  readonly publishingHistory?: PublishingHistory[];
  readonly groupLabels?: Record<string, string>;

  readonly screens?: ScreenDTO[];
  readonly widgets?: WidgetDTO[];
  readonly scripts?: ScriptDTO[];
  readonly theme?: ThemeDTO;
  readonly assets?: AssetDTO[];
  readonly fonts?: FontDTO[];
  readonly config?: ConfigDTO;
  readonly secrets?: SecretDTO;
  readonly translations?: TranslationDTO[];
}

export interface HasLabel {
  readonly labelGroup?: Label;
}

export interface Label {
  readonly id: string;
  readonly name: string;
}

export interface PublishingHistory {
  readonly publishedTo: string;
  readonly createdAt: string;
  readonly publishedBy: string;
  readonly publishingLog: string;
  readonly role: string;
}

export type EnsembleLabeledDocument = EnsembleDocument & HasLabel;

export type ScreenDTO = EnsembleLabeledDocument & {
  readonly type: EnsembleDocumentType.Screen;
  readonly category?: string;
};

export type WidgetDTO = EnsembleLabeledDocument & {
  readonly type: EnsembleDocumentType.Widget;
};

export type ScriptDTO = EnsembleLabeledDocument & {
  readonly type: EnsembleDocumentType.Script;
};

export type ThemeDTO = EnsembleDocument & {
  readonly type: EnsembleDocumentType.Theme;
};

export type TranslationDTO = EnsembleDocument & {
  readonly defaultLocale?: boolean;
};

export interface ConfigDTO {
  readonly envVariables?: Record<string, unknown>;
  readonly baseUrl?: string;
  readonly useBrowserUrl?: boolean;
}

export type SecretDTO = Record<string, unknown>;

export type AssetDTO = EnsembleDocument & {
  readonly type: EnsembleDocumentType.Asset;
  readonly fileName: string;
  readonly publicUrl?: string;
  readonly copyText?: string;
};

export type FontDTO = EnsembleDocument & {
  readonly name?: string;
  readonly fontFamily?: string;
  readonly fontWeight?: string;
  readonly fontStyle?: string;
  readonly fontType?: string;
  readonly publicUrl?: string;
};

export enum AppCategory {
  Demo = 'Demo',
  Template = 'Template',
}

export enum AccessType {
  Read = 'read',
  Write = 'write',
  Owner = 'owner',
}

export type EnsembleDocumentHistoryItem = EnsembleDocument & {
  readonly comment: string;
  readonly label: string;
};

export const ArtifactProps = [
  'screens',
  'widgets',
  'scripts',
  'translations',
  'theme',
] as const;

export type ArtifactProp = (typeof ArtifactProps)[number];
